config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'products' => 'products#index', as: 'products'
  get 'products/:id' => 'products#show', as: 'product', id: /\d+/
  get 'cart' => 'cart#show', as: 'cart'
  resources :line_items, only: [:create, :update, :destroy]
  get 'checkout' => 'checkout#new', as: 'new_checkout'
  post 'checkout' => 'checkout#create', as: 'checkout'
  root to: 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :product_categories

  validates :name, :description, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable

  # belongs_to :province
  has_many :orders

  validates :name, :address, :city, :postal_code, presence: true

  # canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
  # validates :postal_code, format: { with: canadian_postal_code }

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
    def product_present
      if product.nil?
        errors.add(:product, "is not valid or is not ative.")
      end
    end

    def order_present
      if order.nil?
        errors.add(:order, "is not a valid order.")
      end
    end

    def finalize
      self[:unit_price] = unit_price
      self[:total_price] = quantity * self[:unit_price]
    end
end

app/models/order.rb
class Order < ApplicationRecord

  # belongs_to :customer
  has_many :line_items
  belongs_to :order_status
  before_validation :set_order_status
  before_save :update_subtotal

  def subtotal
    line_items.collect { |li| li.valid? ? (li.quantity * li.unit_price) : 0}.sum
  end

  def calculate_total
    total = self.order.subtotal
    # unless @order.pst_rate == 0
    #   total += total * @order.pst_rate
    # end
    #
    # unless @order.gst_rate == 0
    #   total += total * @order.gst_rate
    # end
    #
    # unless @order.hst_rate == 0
    #   total += total * @order.hst_rate
    # end
  end

  private
    def set_order_status
      self.order_status_id = 1
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_categories
  has_many :line_items

  validates :name, :description, :image, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 3 }

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
    where("description LIKE ?", "%#{search}%")
  end

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

  belongs_to :category
  belongs_to :product

  validates :product, :category, presence: true

end

app/models/province.rb
class Province < ApplicationRecord

  has_many :province

  validates :name, presence: true
  validates :pst, :gst, :hst, numericality: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:province_id, :name, :address, :city, :postal_code])
    devise_parameter_sanitizer.permit(:account_update, keys: [:province_id, :name, :address, :city, :postal_code])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @line_items = current_order.line_items
    @order = current_order
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :update_order
  before_action :calculate_total

  def show
    @line_items = current_order.line_items
    @order = current_order

  end

  def new
    @order = current_order
    @amount = @order.total * 100
    @description = "Lori's Fairy Garden"
  end

  def create
    @order = current_order
    @amount = (@order.total * 100).to_i

    @customer = Stripe::Customer.create(email:  params[:stripeEmail],
                                       source: params[:stripeToken])

    @charge = Stripe::Charge.create(:customer    => @customer.id,
                                   :amount      => @amount,
                                   :description => 'Rails stripe customer',
                                   :currency    => 'cad')

    if @charge.paid && @charge.amount == @amount
      @order.update_attribute(:order_status_id, 2)
      session.delete(:order_id)
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_checkout_path
  end

  private
    def update_order
      @order = current_order
      @province = Province.where(:id => current_customer.province_id).first
      @order.update_attributes(:customer_id => current_customer.id, :pst_rate => @province.pst, :gst_rate => @province.gst, :hst_rate => @province.hst)
    end

    def calculate_total
      @order = current_order
      total = @order.subtotal

      hst_amount = 0
      pst_amount = 0
      gst_amount = 0

      unless @order.pst_rate == 0
        pst_amount = (total * @order.pst_rate).round(2)
      end

      unless @order.gst_rate == 0
        gst_amount = (total * @order.gst_rate).round(2)
      end

      unless @order.hst_rate == 0
        hst_amount = (total * @order.hst_rate).round(2)
      end

      total += gst_amount + pst_amount + hst_amount
      @order.update_attribute(:total, total)
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    @order = current_order
    @line_item = @order.line_items.new(line_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.update_attributes(line_item_params)
    @line_items = @order.line_items
  end

  def destroy
    @order = current_order
    @line_item = @order.line_items.find(params[:id])
    @line_item.destroy
    @line_items = @order.line_items
  end

private
  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @line_item = current_order.line_items.new

    if params[:search]
      @products = Product.search(params[:search]).order("name").page(params[:page]).per(10)
    else
      @products = Product.all.order("name").page(params[:page]).per(10)
    end
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s}
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart_row.html.erb
<div class="well">
<div class="row">
  <div class="col-xs-8">
    <h4><%= product.name %></h4>
  </div>
  <div class="col-xs-4">

    <%= form_for line_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency line_item.unit_price %></span></h4>
      <div class="row">
        <div class="col-xs-4">
          <%= f.number_field :quantity, value: line_item.quantity.to_i, class: "form-control", min: 1 %>
          <%= f.hidden_field :product_id, value: product.id %>
        </div>
        <div class="col-xs-8 text-right">
          <div class="btn-group">
            <%= f.submit "Update Quantity", class: "btn btn-primary" %>
            <%= link_to "Delete", line_item, { data: { confirm: "Are you sure you wish to delete the product '#{line_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
          </div>
        </div>
      </div>
      <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency line_item.total_price %></span></h4>
    <% end %>
  </div>
</div>

app/views/cart/_shopping_cart.html.erb
<% if !@line_item.nil? && @line_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @line_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @line_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @line_items.each do |line_item| %>
    <%= render 'cart/cart_row', product: line_item.product, line_item: line_item, show_total: true %>
  <% end %>
<% end %>

app/views/cart/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
  <p><%= number_to_currency @order.subtotal %>
    <% if customer_signed_in? %>
      <li><%= link_to 'Check out', checkout_path %></li>
    <% else %>
        <p> To proceed with checkout please signup or log in.</p>
        <li><%= link_to 'Sign up', new_customer_registration_path %></li>
        <li><%= link_to 'Log in', new_customer_session_path %></li>
    <% end %>
</div>

app/views/checkout/create.html.erb
<h2>Thanks, you paid <strong><%=number_to_currency (@amount.to_f / 100) %></strong>!</h2>

<h3>Stripe Customer</h3>
<%= debug @customer %>

<h3>Stripe Charge</h3>
<%= debug @charge %>

app/views/checkout/new.html.erb
<%= form_tag checkout_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span><%=number_to_currency (@amount / 100) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Lori's Fairy Garden"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>

app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

app/views/line_items/create.js.erb
<% if @order.errors.any? || @line_item.errors.any? %>
  alert("<%= @order.errors.full_messages %>")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/line_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'cart/shopping_cart') %>")

app/views/line_items/update.html.erb
<h1>LineItems#update</h1>
<p>Find me in app/views/line_items/update.html.erb</p>

app/views/line_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'cart/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">
      <%= form_for line_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">

    </div>
  </div>
<% end %>

<h3 class="text-center">Products for Sale</h3>

<%= form_tag(products_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
  <%= submit_tag "Search" %>
<% end %>
<hr>
<%= paginate @products %>
<% if @products.present? %>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do | product | %>
      <%= render "product_row", product: product, line_item: @line_item %>
      <p><%= link_to 'Details', product_path(product) %></p>
    <% end %>
    </div>
  </div>
<% else %>
  <p>There are no products containing the term(s) <%= params[:search] %></p>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.description %></p>
<p><%= image_tag @product.image %></p>
<p><%= link_to 'Back', products_path %></p>