config/routes.rb
Rails.application.routes.draw do

  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'products' => 'products#index', as: 'products'
  get 'products/:id' => 'products#show', as: 'product', id: /\d+/
  get 'cart' => 'cart#show', as: 'cart'
  resources :line_items, only: [:create, :update, :destroy]
  get 'checkout' => 'checkout#new', as: 'new_checkout'
  post 'checkout' => 'checkout#create', as: 'checkout'
  root to: 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :product_categories

  validates :name, :description, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable

  # belongs_to :province
  has_many :orders

  validates :name, :address, :city, :postal_code, presence: true

  # canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/
  # validates :postal_code, format: { with: canadian_postal_code }

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
    def product_present
      if product.nil?
        errors.add(:product, "is not valid or is not ative.")
      end
    end

    def order_present
      if order.nil?
        errors.add(:order, "is not a valid order.")
      end
    end

    def finalize
      self[:unit_price] = unit_price
      self[:total_price] = quantity * self[:unit_price]
    end
end

app/models/order.rb
class Order < ApplicationRecord

  # belongs_to :customer
  has_many :line_items
  belongs_to :order_status
  before_validation :set_order_status
  before_save :update_subtotal

  def subtotal
    line_items.collect { |li| li.valid? ? (li.quantity * li.unit_price) : 0}.sum
  end

  def calculate_total
    total = self.order.subtotal
    # unless @order.pst_rate == 0
    #   total += total * @order.pst_rate
    # end
    #
    # unless @order.gst_rate == 0
    #   total += total * @order.gst_rate
    # end
    #
    # unless @order.hst_rate == 0
    #   total += total * @order.hst_rate
    # end
  end

  private
    def set_order_status
      self.order_status_id = 1
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_categories
  has_many :line_items

  validates :name, :description, :image, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 3 }

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
    where("description LIKE ?", "%#{search}%")
  end

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

  belongs_to :category
  belongs_to :product

  validates :product, :category, presence: true

end

app/models/province.rb
class Province < ApplicationRecord

  has_many :province

  validates :name, presence: true
  validates :pst, :gst, :hst, numericality: true
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @line_items = current_order.line_items
    @order = current_order
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :update_order
  before_action :calculate_total

  def show
    @line_items = current_order.line_items
    @order = current_order

  end

  def new
    @order = current_order
    @amount = @order.total * 100
    @description = "Lori's Fairy Garden"
  end

  def create
    @order = current_order
    @amount = (@order.total * 100).to_i

    @customer = Stripe::Customer.create(email:  params[:stripeEmail],
                                       source: params[:stripeToken])

    @charge = Stripe::Charge.create(:customer    => @customer.id,
                                   :amount      => @amount,
                                   :description => 'Rails stripe customer',
                                   :currency    => 'cad')

    if @charge.paid && @charge.amount == @amount
      @order.update_attribute(:order_status_id, 2)
      session.delete(:order_id)
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_checkout_path
  end

  private
    def update_order
      @order = current_order
      @province = Province.where(:id => current_customer.province_id).first
      @order.update_attributes(:customer_id => current_customer.id, :pst_rate => @province.pst, :gst_rate => @province.gst, :hst_rate => @province.hst)
    end

    def calculate_total
      @order = current_order
      total = @order.subtotal

      hst_amount = 0
      pst_amount = 0
      gst_amount = 0

      unless @order.pst_rate == 0
        pst_amount = (total * @order.pst_rate).round(2)
      end

      unless @order.gst_rate == 0
        gst_amount = (total * @order.gst_rate).round(2)
      end

      unless @order.hst_rate == 0
        hst_amount = (total * @order.hst_rate).round(2)
      end

      total += gst_amount + pst_amount + hst_amount
      @order.update_attribute(:total, total)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @line_item = current_order.line_items.new

    if params[:search]
      @products = Product.search(params[:search]).order("name").page(params[:page]).per(10)
    else
      @products = Product.all.order("name").page(params[:page]).per(10)
    end
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s}
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.line_items.size} Items in Cart (#{number_to_currency current_order.subtotal})", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LorisFairyGarden</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <% if request.ssl? %>
      <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% else %>
      <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%=link_to "Lori's Fairy Gardens", root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav pull-right">
            <% if customer_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_customer.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', edit_customer_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_customer_session_path, method: :delete %></li>
                </ul>
              </li>
              <li class="cart-text"><%= render 'layouts/cart_text' %></li>
            <% else %>
              <li><%= link_to 'Log in', new_customer_session_path %></li>
              <li><%= link_to 'Sign up', new_customer_registration_path %></li>
              <li class="cart-text"><%= render 'layouts/cart_text' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield :top_content %>

    <div class="container">
      <h1><%= yield :header %></h1>
      <%= yield %>
    </div>


  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>